flowchart LR
  A[Alerta]
  StatsD[StatsD]
  Swift[(Logs)]
  Graphite[GraphiteDB]
  M[Metric Processor]
  Grafana[Grafana Dashboard]
  DB1[(SQL Database)]
  SD[Status Dashboard]
  
  subgraph tester ["Testing framework"]
    direction LR
    subgraph apimon ["StackMon plugin ApiMon"]
      SCH[Scheduler]
      EX[Executor\n X,Y,..]
      subgraph Ansible
          style Ansible stroke:#333,stroke-width:3px;
          P[Playbook]
          SDK[Openstack SDK]
      end
    end
  
    subgraph epmon ["StackMon plugin EpMon"]
      direction LR
      E[Endpoint Monitor]
    end
  
    C[StackMon\n plugin X,Y,..]
  end
  
  subgraph backend ["Backend"]
    direction LR
    A
    StatsD
    Graphite
    M
    DB1
    Swift
  end
  
  subgraph frontend ["Representation layer"]
    direction LR
    Grafana
    SD
  end
  
  tester --> backend
  backend --> frontend

