---
name: PR preview
concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-preview:

    runs-on: ubuntu-latest

    steps:
      - name: Install pandoc
        uses: pandoc/actions/setup@v1.0.0
        with:
          version: 3.1.13

      - uses: actions/checkout@v4

      - name: Build
        run: make
        if: github.event.action != 'closed'

      - name: Debug
        run: find . -type f

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview-action
          action: auto
